-- ALTER TYPE public.app_permission ADD VALUE 'user_tokens.select.company';
-- ALTER TYPE public.app_permission ADD VALUE 'user_tokens.update.company';
-- ALTER TYPE public.app_permission ADD VALUE 'user_tokens.delete.company';
-- ALTER TYPE public.app_permission ADD VALUE 'user_tokens.insert.company';
-- ALTER TYPE public.app_permission ADD VALUE 'user_tokens.select.own';
--
-- insert into public.role_permissions (role_id, permission)
-- values
--    ((SELECT id FROM roles WHERE role_name = 'admin'), 'user_tokens.select.company'),
--    ((SELECT id FROM roles WHERE role_name = 'admin'), 'user_tokens.update.company'),
--    ((SELECT id FROM roles WHERE role_name = 'admin'), 'user_tokens.delete.company'),
--    ((SELECT id FROM roles WHERE role_name = 'admin'), 'user_tokens.insert.company'),
--    ((SELECT id FROM roles WHERE role_name = 'moderator'), 'user_tokens.select.own');
--
--
